name: CI

on:
  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        platform: [ios, macos, android, windows, linux]
        include:
          - platform: ios
            os: macos-latest
            desktop: false
          - platform: macos
            os: macos-latest
            desktop: true
          - platform: android
            os: macos-latest
            desktop: false
          - platform: windows
            os: windows-latest
            desktop: true
          - platform: linux
            os: ubuntu-latest
            desktop: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      ## iOS integration
      - name: Start up iOS Simulator
        if: ${{ matrix.platform == 'ios' }}
        uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 8'

      ## macOS, Windows and Linux integration
      - name: Enable desktop support
        if: ${{ matrix.desktop }}
        run: |
          flutter config --enable-windows-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-linux-desktop

      ## Linux integration
      - name: Install Linux dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libglu1-mesa clang cmake pkg-config xvfb

      - name: Run Flutter Doctor
        run: flutter doctor
      - name: Install dependencies
        run: flutter pub get

      ## Non-Android integration
      - name: Run tests
        if: ${{ matrix.platform != 'android' }}
        working-directory: ./example
        run: |
          Xvfb :1 -screen 0 640x480x24 -fbdir /var/tmp&
          export DISPLAY=localhost:1.0
          xdpyinfo -display :0 >/dev/null 2>&1 && echo "In use" || echo "Free"
          flutter test integration_test

      ## Android integration
      - name: Run tests on Android Emulator
        if: ${{ matrix.platform == 'android' }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          working-directory: ./example
          script: flutter test integration_test