name: Dart CI

on:
  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  integration_macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        working-directory: ./example
        run: flutter test integration_test -d macos